### ISSUE TITLE
Lost target tracker

### ISSUE THREAD

**Issue by dylan906** [dylan906/clockpunch#10]
Build a lost target tracker (put in common dir). 

- Stores all target custody as a bool.
- Updates target custody based on estimate covariance
  - Input whole matrix, but possibly have options for how the determination is made.
  - Default should be based on max positional std (out of I, J, K components).
  - Other options could include trace of whole matrix/positional/velocity components.
- Set a threshold on instantiation for what counts as "in custody"

Update:
3 components to the tracker:

- [x] core tracker: Updates custody list given a single time step observation. The logic of declaring a target in/out of custody is configurable with either an arbitrary `Callable` or setting one of a predefined list of (for now) covariance-based functions.
- [x] custody wrapper: Observation space wrapper that adds `"custody"` as an item in a `Dict` observation space.
- [x] action mask insertion wrapper: Observation space wrapper that modifies `"action_mask"` entry in observation space by incorporating `"custody"`. This converts action masking from being exclusively a function of estimated visibility to an arbitrary masking that can be affected by other bits from the observation space.
